name: Update README fastfetch

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Update README using script
        run: |
          chmod +x ./update_readme.sh
          ./update_readme.sh
      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "chore: update fastfetch in README" || echo "No changes to commit"
          git push
